### ISSUE TITLE
3 Errors

### ISSUE THREAD

**Issue by Prog-Maker** [dance2die/ReactES6.Web#2]
After run have 3 errors

ERROR in ./ClientApp/components/Home.js
Module not found: Error: Can't resolve 'react-router' in 'C:\Users\Admin\Desktop\reactAspCoreTemplate\NewSite.Web\ClientApp\components'
 @ ./ClientApp/components/Home.js 14:19-42
 @ ./ClientApp/routes.js
 @ ./ClientApp/boot.js
 @ multi react-hot-loader/patch event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.js
ERROR in ./ClientApp/components/Counter.js
Module not found: Error: Can't resolve 'react-router' in 'C:\Users\Admin\Desktop\reactAspCoreTemplate\NewSite.Web\ClientApp\components'
 @ ./ClientApp/components/Counter.js 14:19-42
 @ ./ClientApp/routes.js
 @ ./ClientApp/boot.js
 @ multi react-hot-loader/patch event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.js
ERROR in ./ClientApp/components/FetchData.js
Module not found: Error: Can't resolve 'react-router' in 'C:\Users\Admin\Desktop\reactAspCoreTemplate\NewSite.Web\ClientApp\components'
 @ ./ClientApp/components/FetchData.js 14:19-42
 @ ./ClientApp/routes.js
 @ ./ClientApp/boot.js
 @ multi react-hot-loader/patch event-source-polyfill webpack-hot-middleware/client?path=__webpack_hmr&dynamicPublicPath=true ./ClientApp/boot.js

**Comment by dance2die** [comment]
@Prog-Maker Thanks for reporting 👍 .

I was able to reproduce the issue.
I will take a look at it 😎 .

**Comment by dance2die** [comment]
@Prog-Maker The issue has been resolved in pull request #3 .

Version 0.1.0 fixes the issue.
